#!/usr/bin/env bash
# Comad World Upgrader
#
# Upgrades an existing Comad World installation: main repo + 6 module repos,
# dependencies, agents, and configs. Designed to be safe by default — aborts
# on dirty working trees, snapshots mutable state before touching anything,
# and prints a timed, per-module summary at the end.
#
# Usage:
#   scripts/upgrade.sh                  # full upgrade
#   scripts/upgrade.sh --dry-run        # show what would happen, no changes
#   scripts/upgrade.sh --force          # override dirty working tree abort
#   scripts/upgrade.sh --rollback <ts>  # restore a previous backup
#   scripts/upgrade.sh --list-backups
#   scripts/upgrade.sh --lock           # regenerate comad.lock from current SHAs
#
# Exit codes:
#   0  success
#   1  precondition failed (dirty tree, missing tool, etc.)
#   2  partial failure (one or more modules failed to update)
#   3  rollback failure
#
set -euo pipefail

# ─── Colors ───
if [ -t 1 ]; then
  CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
  RED='\033[0;31m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'
else
  CYAN=''; GREEN=''; YELLOW=''; RED=''; BOLD=''; DIM=''; NC=''
fi

info()  { printf "  ${GREEN}✓${NC} %s\n" "$1"; }
warn()  { printf "  ${YELLOW}!${NC} %s\n" "$1"; }
fail()  { printf "  ${RED}✗${NC} %s\n" "$1"; }
step()  { printf "\n${BOLD}%s${NC}\n" "$1"; }
dim()   { printf "${DIM}%s${NC}\n" "$1"; }

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MODULES=(brain ear eye photo sleep voice)

DRY_RUN=0; FORCE=0; ROLLBACK_TS=""; LIST_BACKUPS=0; LOCK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --dry-run)        DRY_RUN=1 ;;
    --force)          FORCE=1 ;;
    --rollback)       ROLLBACK_TS="NEXT" ;;
    --list-backups)   LIST_BACKUPS=1 ;;
    --lock)           LOCK_ONLY=1 ;;
    -h|--help)
      sed -n '3,22p' "$0" | sed 's/^# //;s/^#//'; exit 0 ;;
    *)
      if [ "$ROLLBACK_TS" = "NEXT" ]; then ROLLBACK_TS="$arg"; continue; fi
      fail "Unknown argument: $arg"; exit 1 ;;
  esac
done

run() {
  # run <description> -- <command...>
  local desc="$1"; shift
  [ "$1" = "--" ] && shift
  if [ "$DRY_RUN" = "1" ]; then
    dim "    would run: $*"
    return 0
  fi
  "$@"
}

timed() {
  # timed <label> -- <command...>
  local label="$1"; shift
  [ "$1" = "--" ] && shift
  local start elapsed
  start=$(date +%s)
  if "$@"; then
    elapsed=$(( $(date +%s) - start ))
    printf "  ${GREEN}✓${NC} %-24s ${DIM}(%ss)${NC}\n" "$label" "$elapsed"
    return 0
  else
    elapsed=$(( $(date +%s) - start ))
    printf "  ${RED}✗${NC} %-24s ${DIM}(%ss)${NC}\n" "$label" "$elapsed"
    return 1
  fi
}

# ─── Banner ───
CURRENT_VERSION="$(cat VERSION 2>/dev/null || echo 'unknown')"
printf "${CYAN}╔══════════════════════════════════════╗${NC}\n"
printf "${CYAN}║       Comad World Upgrader          ║${NC}\n"
printf "${CYAN}║       v%-30s║${NC}\n" "$CURRENT_VERSION"
printf "${CYAN}╚══════════════════════════════════════╝${NC}\n"
[ "$DRY_RUN" = "1" ] && warn "DRY-RUN mode — no changes will be made"

# ─── --lock: regenerate comad.lock ───
if [ "$LOCK_ONLY" = "1" ]; then
  step "Regenerating comad.lock"
  {
    echo "# Comad World Lockfile"
    echo "# Pinned SHAs for each module. Regenerated by \`scripts/upgrade.sh --lock\`."
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo
    echo "main:"
    echo "  repo: comad-world"
    echo "  branch: $(git branch --show-current)"
    echo "  sha: $(git rev-parse HEAD)"
    echo
    echo "modules:"
    for m in "${MODULES[@]}"; do
      if [ -d "$m/.git" ] || [ -f "$m/.git" ]; then
        echo "  $m:"
        echo "    remote: $(git -C "$m" remote get-url origin)"
        echo "    branch: $(git -C "$m" branch --show-current)"
        echo "    sha: $(git -C "$m" rev-parse HEAD)"
      else
        echo "  $m: # missing"
      fi
    done
  } > comad.lock
  info "Wrote $(pwd)/comad.lock"
  exit 0
fi

# ─── --list-backups ───
if [ "$LIST_BACKUPS" = "1" ]; then
  step "Available backups"
  if [ ! -d .comad/backups ]; then
    warn "No backups found under .comad/backups/"
    exit 0
  fi
  ls -1 .comad/backups | while read -r ts; do
    size=$(du -sh ".comad/backups/$ts" 2>/dev/null | awk '{print $1}')
    echo "  $ts  ($size)"
  done
  exit 0
fi

# ─── --rollback <ts> ───
if [ -n "$ROLLBACK_TS" ] && [ "$ROLLBACK_TS" != "NEXT" ]; then
  step "Rolling back to $ROLLBACK_TS"
  BACKUP_DIR=".comad/backups/$ROLLBACK_TS"
  if [ ! -d "$BACKUP_DIR" ]; then
    fail "Backup not found: $BACKUP_DIR"
    echo "  Run: $0 --list-backups"
    exit 3
  fi
  [ "$DRY_RUN" = "1" ] && { dim "would restore $BACKUP_DIR → project"; exit 0; }
  for target in comad.config.yaml comad.lock VERSION; do
    if [ -f "$BACKUP_DIR/$target" ]; then
      cp "$BACKUP_DIR/$target" "$target"
      info "Restored $target"
    fi
  done
  if [ -f "$BACKUP_DIR/env" ]; then cp "$BACKUP_DIR/env" .env && info "Restored .env"; fi
  if [ -d "$BACKUP_DIR/agents" ]; then
    mkdir -p "$HOME/.claude/agents"
    cp -R "$BACKUP_DIR/agents/." "$HOME/.claude/agents/"
    info "Restored ~/.claude/agents/"
  fi
  warn "Submodule code is NOT rolled back (use: git -C <module> checkout <sha> from comad.lock backup)"
  info "Rollback complete. Review with: git status"
  exit 0
fi

# ─── Step 1: Pre-flight checks ───
step "[1/6] Pre-flight checks"

# 1a. Tools
for tool in git curl; do
  command -v "$tool" >/dev/null 2>&1 || { fail "Required: $tool"; exit 1; }
done
info "Required tools present (git, curl)"

# 1b. Dirty working tree (main + modules)
DIRTY_FOUND=0
check_dirty() {
  local dir="$1"; local label="$2"
  if [ -n "$(git -C "$dir" status --porcelain 2>/dev/null)" ]; then
    warn "$label has uncommitted changes"
    DIRTY_FOUND=1
  fi
}
check_dirty "." "main repo"
for m in "${MODULES[@]}"; do
  [ -d "$m/.git" ] || [ -f "$m/.git" ] && check_dirty "$m" "$m"
done
if [ "$DIRTY_FOUND" = "1" ] && [ "$FORCE" = "0" ]; then
  echo ""
  fail "Dirty working tree detected. Commit/stash changes, or re-run with --force."
  exit 1
fi
[ "$DIRTY_FOUND" = "0" ] && info "Working trees clean"

# 1c. Running services (warn only)
RUNNING=()
for port_label in "8000:eye-api" "3000:eye-web" "7687:eye-neo4j" "7688:brain-neo4j"; do
  port="${port_label%:*}"; label="${port_label#*:}"
  if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
    RUNNING+=("$label ($port)")
  fi
done
if [ "${#RUNNING[@]}" -gt 0 ]; then
  warn "Running services detected: ${RUNNING[*]}"
  echo "    Upgrade will proceed, but restart services afterwards to pick up new code."
else
  info "No Comad services running"
fi

# 1d. .env new-key diff (if .env.example changed upstream)
if [ -f .env ] && [ -f .env.example ]; then
  missing=$(grep -v '^#' .env.example | grep '=' | awk -F= '{print $1}' | while read -r k; do
    grep -q "^$k=" .env || echo "$k"
  done)
  if [ -n "$missing" ]; then
    warn "New keys in .env.example not present in .env:"
    echo "$missing" | sed 's/^/      /'
    echo "      (add them after upgrade, or run \`cp .env.example .env.new\` to compare)"
  fi
fi

# ─── Step 2: Snapshot ───
step "[2/6] Snapshotting mutable state"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_DIR=".comad/backups/$TS"
if [ "$DRY_RUN" = "1" ]; then
  dim "    would snapshot to $BACKUP_DIR"
else
  mkdir -p "$BACKUP_DIR"
  for src in comad.config.yaml comad.lock VERSION .env; do
    [ -f "$src" ] && cp "$src" "$BACKUP_DIR/${src#.}" 2>/dev/null || true
    [ "$src" = ".env" ] && [ -f "$src" ] && cp "$src" "$BACKUP_DIR/env" 2>/dev/null || true
  done
  if [ -d "$HOME/.claude/agents" ]; then
    mkdir -p "$BACKUP_DIR/agents"
    cp -R "$HOME/.claude/agents/." "$BACKUP_DIR/agents/" 2>/dev/null || true
  fi
  info "Snapshot: $BACKUP_DIR"
fi

# ─── Step 3: Update main + modules ───
step "[3/6] Pulling latest"
declare -a RESULTS

pull_repo() {
  local dir="$1"; local label="$2"
  local before after branch
  before=$(git -C "$dir" rev-parse HEAD 2>/dev/null || echo "?")
  branch=$(git -C "$dir" branch --show-current 2>/dev/null || echo "?")
  if [ "$DRY_RUN" = "1" ]; then
    dim "    would: git -C $dir pull --ff-only origin $branch"
    RESULTS+=("$label: dry-run")
    return 0
  fi
  if git -C "$dir" pull --ff-only origin "$branch" >/tmp/upgrade-pull-$$.log 2>&1; then
    after=$(git -C "$dir" rev-parse HEAD)
    if [ "$before" = "$after" ]; then
      RESULTS+=("$label: up-to-date")
    else
      RESULTS+=("$label: ${before:0:8} → ${after:0:8}")
    fi
    return 0
  else
    RESULTS+=("$label: FAIL ($(tail -1 /tmp/upgrade-pull-$$.log))")
    return 1
  fi
}

timed "main repo" -- pull_repo "." "main" || true
for m in "${MODULES[@]}"; do
  if [ -d "$m/.git" ] || [ -f "$m/.git" ]; then
    timed "$m" -- pull_repo "$m" "$m" || true
  else
    RESULTS+=("$m: SKIP (not cloned)")
    warn "$m not cloned — skipped"
  fi
done

# ─── Step 4: Dependencies ───
step "[4/6] Reinstalling dependencies"

if [ -d brain ] && [ -f brain/package.json ]; then
  if command -v bun >/dev/null 2>&1; then
    timed "brain (bun install)" -- bash -c "cd brain && { if [ '$DRY_RUN' = '1' ]; then echo 'would bun install'; else bun install --silent; fi; }" || warn "brain deps failed"
  else
    warn "brain: bun not installed — skipping"
  fi
fi

if [ -d eye ] && [ -f eye/requirements.txt ]; then
  PY_BIN="python3"
  if [ -f eye/.venv/bin/python ]; then PY_BIN="eye/.venv/bin/python"; fi
  if command -v "$PY_BIN" >/dev/null 2>&1; then
    timed "eye (pip install)" -- bash -c "if [ '$DRY_RUN' = '1' ]; then echo 'would pip install'; else $PY_BIN -m pip install --quiet -r eye/requirements.txt; fi" || warn "eye deps failed"
  fi
fi

if [ -d eye/frontend ] && [ -f eye/frontend/package.json ]; then
  if command -v npm >/dev/null 2>&1; then
    timed "eye-frontend (npm ci)" -- bash -c "cd eye/frontend && { if [ '$DRY_RUN' = '1' ]; then echo 'would npm ci'; else npm ci --silent --no-audit --no-fund; fi; }" || warn "eye frontend deps failed"
  fi
fi

# ─── Step 5: Agents + Config ───
step "[5/6] Redeploying agents & configs"

mkdir -p "$HOME/.claude/agents"
redeploy_agent() {
  local src="$1"; local name="$2"
  if [ -f "$src" ]; then
    if [ "$DRY_RUN" = "1" ]; then dim "    would copy $src → ~/.claude/agents/"; return; fi
    cp "$src" "$HOME/.claude/agents/"
    info "Redeployed $name"
  fi
}
redeploy_agent "sleep/comad-sleep.md" "comad-sleep"
redeploy_agent "photo/core/comad-photo.md" "comad-photo"

# Voice: replace only between markers
if [ -f voice/core/comad-voice.md ]; then
  CLAUDE_MD="$HOME/.claude/CLAUDE.md"
  if [ -f "$CLAUDE_MD" ] && grep -q "COMAD-VOICE:START" "$CLAUDE_MD" 2>/dev/null; then
    if [ "$DRY_RUN" = "1" ]; then
      dim "    would replace voice section in $CLAUDE_MD"
    else
      python3 - <<PY
import pathlib, re
p = pathlib.Path("$CLAUDE_MD")
txt = p.read_text()
new = pathlib.Path("voice/core/comad-voice.md").read_text()
pattern = re.compile(r"<!-- COMAD-VOICE:START -->.*?<!-- COMAD-VOICE:END -->", re.DOTALL)
if pattern.search(txt):
    txt = pattern.sub(new.strip(), txt)
    p.write_text(txt)
    print("  \033[0;32m✓\033[0m Updated voice section in ~/.claude/CLAUDE.md")
else:
    print("  \033[1;33m!\033[0m Voice markers not found — skipping (run install.sh to add)")
PY
    fi
  else
    warn "Voice not installed (no COMAD-VOICE markers in ~/.claude/CLAUDE.md)"
  fi
fi

# Regenerate module configs
if command -v yq >/dev/null 2>&1 && [ -f scripts/apply-config.sh ]; then
  if [ "$DRY_RUN" = "1" ]; then dim "    would run scripts/apply-config.sh"; else
    timed "apply-config.sh" -- bash scripts/apply-config.sh >/dev/null 2>&1 || warn "apply-config.sh failed"
  fi
else
  warn "yq not installed — skipping config regeneration"
fi

# Render path-aware templates so the repo keeps working at its current location
# (handles e.g. sleep/.mcp.json which embeds the absolute repo path).
if [ -f scripts/render-templates.sh ]; then
  if [ "$DRY_RUN" = "1" ]; then
    dim "    would run scripts/render-templates.sh"
  else
    timed "render-templates.sh" -- bash scripts/render-templates.sh >/dev/null 2>&1 || warn "render-templates.sh failed"
  fi
fi

# ─── Step 6: Summary ───
step "[6/6] Summary"

echo ""
printf "  ${BOLD}Module updates:${NC}\n"
for line in "${RESULTS[@]}"; do
  if [[ "$line" == *FAIL* ]]; then
    printf "    ${RED}✗${NC} %s\n" "$line"
  elif [[ "$line" == *SKIP* ]]; then
    printf "    ${YELLOW}!${NC} %s\n" "$line"
  else
    printf "    ${GREEN}✓${NC} %s\n" "$line"
  fi
done

# CHANGELOG diff (new entries since previous VERSION)
if [ -f CHANGELOG.md ] && [ "$DRY_RUN" = "0" ]; then
  echo ""
  printf "  ${BOLD}What's new (CHANGELOG.md):${NC}\n"
  awk "/^## \[$CURRENT_VERSION\]/{found=1; next} /^## \[/{if(found)exit} found" CHANGELOG.md 2>/dev/null \
    | head -20 | sed 's/^/    /' || true
fi

# Regenerate comad.lock
if [ "$DRY_RUN" = "0" ]; then
  bash "$0" --lock >/dev/null 2>&1 || true
  info "Regenerated comad.lock"
fi

echo ""
printf "  ${BOLD}Next steps:${NC}\n"
echo "    1. Review changes:  git diff"
echo "    2. Restart services: docker compose down && docker compose up -d"
echo "    3. Rollback if needed: $0 --rollback $TS"
echo ""
FAILED_COUNT=$(printf '%s\n' "${RESULTS[@]}" | grep -c FAIL || true)
if [ "$FAILED_COUNT" -gt 0 ]; then
  fail "$FAILED_COUNT module(s) failed. See details above."
  exit 2
fi
info "Upgrade complete."
